# Generated by Django 5.2 on 2025-04-07 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('requisitos', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('reclutador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
